### ISSUE TITLE
Panic permission denied

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [mapitman/mdview#32]
```
$ mdview  foobar.md 
panic: open foobar.md: permission denied

goroutine 1 [running]:
main.check(...)
	/build/mdview/parts/mdview/build/main.go:116
main.main()
	/build/mdview/parts/mdview/build/main.go:49 +0x70b
```

**Comment by mapitman** [comment]
How did you install mdview and which version is it?

**Comment by i-n-g-m-a-r** [comment]
> How did you install mdview and which version is it?

`sudo snap install mdview`
`1.6.2`

**Comment by mapitman** [comment]
Sorry it's taken so long to get back to you. I've had some personal/family issues going on.

This is what happens when you try to open a file outside of your home directory. Snaps are strictly confined and I am only adding the [home interface](https://snapcraft.io/docs/home-interface) as part of the snap creation.

If you would like to use it for files anywhere on your system, you can either use [deb-get](https://github.com/wimpysworld/deb-get) to install mdview or download the [latest](https://github.com/mapitman/mdview/releases/tag/1.6.2) deb package and install it manually.

**Comment by mapitman** [comment]
Reopening. I'll see if I can add a more descriptive error message.
