### ISSUE TITLE
Error message on first use after install

### ISSUE THREAD

**Issue by chrisveness** [mapitman/mdview#7]
The first time I ran `mdview` after installation (using snap) I got a strange error:

```
$ sudo snap install mdview
[sudo] password for [...]: 
mdview 1.3.0 from Mark Pitman (markpitman) installed
$ mdview mymarkdown.md 
user-open error: Object does not implement the interface
panic: exit status 1

goroutine 1 [running]:
main.check(0x6275a0, 0xc4201398a0)
	/build/mdview/parts/mdview/go/src/mdview/main.go:89 +0x4a
main.main()
	/build/mdview/parts/mdview/go/src/mdview/main.go:71 +0x6e0
```
Subsequent invocations worked fine (though there is a rather annoying "Allow opening file?" dialog box).

- `/etc/os-release`: Linux Mint 18
- `/etc/upstream-release/lsb-release`: Ubuntu 16.04 LTS

**Comment by mapitman** [comment]
I've noticed the error you are talking about as well, although, since it was not consistent, I thought it was something specific to my setup. I'll take a look at that.

As for the annoying "Allow opening file?" dialog, that is related to snaps in general. They are sandboxed by default. If you have Go installed on your computer, you may want to try just installing directly via `go get github.com/mapitman/mdview`.

**Comment by mapitman** [comment]
After doing a little more investigation, this error message only happens when using the snap. It seems to happen the first time using it after a reboot. I'm not really sure how to debug it yet.

**Comment by chrisveness** [comment]
It doesn't seem too serious – I reported it mostly just so you would be aware of it, it doesn't really bother me particularly!

**Comment by mapitman** [comment]
OK, thanks! I'll leave this open for now as a reminder to see if I can solve it.

**Comment by mapitman** [comment]
I'm not seeing this error anymore. How about you?
